### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by cheyiliu** [dkmeteor/SmoothTransition#2]
many OOM occurs when select from menu,
09-29 09:35:34.707: E/AndroidRuntime(8997): java.lang.OutOfMemoryError
...

**Comment by dkmeteor** [comment]
Could you help give me more information? @cheyiliu 
Android Version,Emulator or Device,Full Error Stack or any other information can help me to locate the error.

**Comment by cheyiliu** [comment]
Hi @dkmeteor , I run the code on XiaoMi 1s and click the menu item "scale", "rotate" etc. then got the OOM. the trace is shwon below 

```
09-29 16:25:16.177: I/dalvikvm(21183):   at dalvik.system.NativeStart.main(Native Method)
09-29 16:25:16.177: W/dalvikvm(21183): threadid=1: thread exiting with uncaught exception (group=0x410c29d8)
09-29 16:25:16.187: E/AndroidRuntime(21183): FATAL EXCEPTION: main
09-29 16:25:16.187: E/AndroidRuntime(21183): java.lang.OutOfMemoryError
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.Bitmap.nativeCreate(Native Method)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.Bitmap.createBitmap(Bitmap.java:605)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.Bitmap.createBitmap(Bitmap.java:551)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:437)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:524)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:499)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.content.res.Resources.loadDrawable(Resources.java:1944)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.content.res.Resources.getDrawable(Resources.java:668)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.ImageView.resolveUri(ImageView.java:542)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.ImageView.setImageResource(ImageView.java:315)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at com.dk.sample.GridActivity$GridAdapter.getView(GridActivity.java:116)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.AbsListView.obtainView(AbsListView.java:2047)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.GridView.makeAndAddView(GridView.java:1323)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.GridView.makeRow(GridView.java:328)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.GridView.fillDown(GridView.java:281)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.GridView.fillFromTop(GridView.java:403)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.GridView.layoutChildren(GridView.java:1215)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.AbsListView.onLayout(AbsListView.java:1877)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.View.layout(View.java:11288)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1629)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1487)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1400)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.View.layout(View.java:11288)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.View.layout(View.java:11288)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1629)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1487)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1400)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.View.layout(View.java:11288)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.View.layout(View.java:11288)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewGroup.layout(ViewGroup.java:4224)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1494)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2447)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.os.Looper.loop(Looper.java:137)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at android.app.ActivityThread.main(ActivityThread.java:4439)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at java.lang.reflect.Method.invokeNative(Native Method)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at java.lang.reflect.Method.invoke(Method.java:511)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
09-29 16:25:16.187: E/AndroidRuntime(21183):    at dalvik.system.NativeStart.main(Native Method)

```
